import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'user_profile_entity.schema.dart';

@Model(tableName: 'UserProfile')
abstract class UserProfileEntity {
  @PrimaryKey()
  String get id;

  int? get role;

  String? get email;

  String? get phone;

  String? get avatarUrl;

  String? get name;

  DateTime? get birthDate;

  DateTime? get lastTimeUpdate;

}