name: auth_service
description: authentication service
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_jsonwebtoken: ^2.7.1
  dart_frog: ^0.3.0
  dbcrypt: ^2.0.0
  uuid: ^3.0.7
  json_serializable: ^6.6.2
  stormberry:
    git:
      url: https://github.com/MinhMark123123/stormberry.git
  database_service:
    git:
      url: https://github.com/MinhMark123123/compack_server.git
      ref: feature/refactor-melos-config-packages-again
      path: packages/database_service

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
