name: database_service
description: Database service description
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  stormberry:
    git:
      url: https://github.com/MinhMark123123/stormberry.git
  json_serializable: ^6.6.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
