name: compack_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  stormberry:
    git:
      url: https://github.com/MinhMark123123/stormberry.git
  dbcrypt: ^2.0.0
  uuid: ^3.0.7
  dart_jsonwebtoken: ^2.7.1
  in_memory_todos_data_source:
    path: packages/in_memory_todos_data_source
  todos_data_source:
    path: packages/todos_data_source
  json_serializable: ^6.6.2
  database_service:
    git:
      url: https://github.com/MinhMark123123/compack_server.git
      ref: feature/refactor-melos-config-packages-again
      path: packages/database_service
  auth_service:
    git:
      url: https://github.com/MinhMark123123/compack_server.git
      ref: feature/refactor-melos-config-packages-again
      path: packages/database_service

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
