import 'package:auth_service/src/data/models/models.dart';
import 'package:stormberry/stormberry.dart';

// Will be generated by stormberry
part 'user_entity.schema.dart';

@Model(tableName: 'User')
abstract class UserEntity {
  @PrimaryKey()
  String get id;

  String? get email;

  String? get phone;

  String? get password;

  String? get token;

  String? get refreshToken;

  DateTime? get timeCreated;

  DateTime? get lastLogonTime;

  DateTime? get lastTimeUpdate;

}
